return {
  ["workshop-1207269058"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=10,
      hbpos=1,
      hbstyle="heart",
      value=true 
    },
    enabled=true 
  },
  ["workshop-1349799880"]={
    configuration_options={
      language="en",
      loot_percent=0.75,
      menu_divider1=false,
      menu_divider2=false,
      menu_divider3=false,
      menu_divider4=false,
      mist=1,
      recipe_ingredients="12/68/20",
      recipe_tab="SCIENCE",
      recipe_tech="SCIENCE_TWO",
      sanity=-5,
      temperature=-25 
    },
    enabled=true 
  },
  ["workshop-421029894"]={
    configuration_options={ key_disorganized=121, key_paranoid=99, key_psychotic=120 },
    enabled=true 
  },
  ["workshop-791838548"]={
    configuration_options={
      Dispenser_Difficulty="default",
      EHat_Difficulty="default",
      Scrap_Difficulty="default",
      Sentry_Damage=9.5,
      Sentry_Difficulty="default",
      Sentry_Health=200,
      Sentry_ROF=1,
      Sentry_Range=13,
      Teleporter_Difficulty="default",
      buildinglimit="n",
      dispenseramount=4,
      dispenserhealingrate=3,
      dispenserlimit="n",
      disprange=2,
      ehardhatdura=295,
      engiedmgdebuff=0.8,
      hardhatabsorb=0.7,
      rocketsplashdmg="y",
      sentryamount=4,
      sentryh_regen="n",
      sentrylimit="n",
      teleporteramount=4,
      teleporterlimit="n",
      tf2Wrench_Difficulty="default",
      tf2wrenchdmg=17,
      tf2wrenchuses=150 
    },
    enabled=true 
  } 
}